import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta
        property="og:title"
        content="How to change the address bar color in Chrome, Firefox, Opera, Safari"
      />
      <meta
        property="og:description"
        content="How to change the address bar color in Chrome, Firefox, Opera, Safari"
      />
      <meta
        property="og:url"
        content="https://random-image-share.vercel.app/"
      />
      <meta
        property="og:image"
        content="http://webdevelopmentscripts.com/post-images/685b-change-browser-address-bar-color-chrome-android.jpeg"
      />
      <meta property="twitter:image" content="https://www.webdevelopmentscripts.com/post-images/685b-change-browser-address-bar-color-chrome-android.jpeg"></meta>
      <meta property="twitter:card" content="summary_large_image"></meta>
      <meta property="twitter:title" content="Twitter link preview title"></meta>
      <meta property="twitter:description" content="Twitter link preview description"></meta>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
